import { motion } from 'framer-motion';
import { Check, FileCheck2, ThumbsUp, UserRoundCheck } from 'lucide-react';

export function Scene5() {
  return (
    <motion.section className="relative h-screen w-full overflow-hidden" initial={{ opacity: 0, rotateY: 9, x: 60 }} animate={{ opacity: 1, rotateY: 0, x: 0 }} exit={{ opacity: 1, rotateY: -9, x: -60 }} transition={{ duration: .8, ease: [0.16, 1, 0.3, 1] }}>
      <div className="absolute inset-0 bg-[linear-gradient(135deg,#191f25,#24262a)]" />
      <div className="absolute bottom-[-20vw] left-[28vw] h-[58vw] w-[58vw] rounded-full border border-[rgba(231,182,108,.16)]" />
      <div className="absolute left-[4.4vw] top-[18vh] max-w-[34vw]"><div className="caption mb-[2.4vh] text-[var(--amber)]">04 / Keep humans in the loop</div><h2 className="display-lg">Good AI<br /><span className="text-[var(--amber)]">shows its work.</span></h2><p className="body-sm mt-[3vh] max-w-[23vw] text-[var(--paper-dim)]">Operators accept, correct, or reject the diagnosis. Every decision feeds the next shift.</p><motion.div className="mt-[4vh] flex items-center gap-[.65vw] text-[var(--amber)]" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.2, duration: .5 }}><UserRoundCheck size="1.1vw" /><span className="mono text-[clamp(8px,.65vw,11px)]">ALEX RIVERA · REVIEWER</span></motion.div></div>
      <motion.div className="absolute right-[5vw] top-[17vh] w-[48vw] rounded-[.45vw] border border-[var(--line)] bg-[rgba(21,27,32,.82)] p-[1.25vw] backdrop-blur" initial={{ opacity: 0, y: 32, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ delay: .38, duration: .85, ease: [0.16, 1, 0.3, 1] }}>
        <div className="flex items-center justify-between border-b border-[var(--line)] pb-[1vw]"><div><div className="mono text-[clamp(7px,.52vw,10px)] text-[var(--muted)]">AUDIT ACTION / C001</div><div className="mt-[.3vw] text-[clamp(13px,1.2vw,20px)] font-semibold">Record human review</div></div><div className="grid h-[2.2vw] w-[2.2vw] place-items-center rounded-full bg-[rgba(231,182,108,.14)] text-[var(--amber)]"><UserRoundCheck size="1.1vw" /></div></div>
        <div className="mt-[1.1vw] grid grid-cols-2 gap-[.75vw]"><motion.div className="rounded-[.3vw] border border-[rgba(226,111,88,.25)] bg-[rgba(226,111,88,.045)] p-[.9vw]" initial={{ opacity: 0, x: -15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .75, duration: .5 }}><div className="mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">MODEL OUTPUT</div><div className="mt-[.7vw] text-[clamp(10px,.83vw,14px)] font-semibold leading-[1.25]">Native VLAN mismatch on the trunk link</div><div className="mt-[1vw] flex items-center gap-[.5vw] text-[var(--coral)]"><span className="mono text-[clamp(7px,.55vw,10px)]">92% CONFIDENCE</span></div></motion.div><motion.div className="rounded-[.3vw] border border-[rgba(131,184,171,.3)] bg-[rgba(131,184,171,.05)] p-[.9vw]" initial={{ opacity: 0, x: 15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .9, duration: .5 }}><div className="mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">OPERATOR DECISION</div><div className="mt-[.7vw] flex items-center gap-[.6vw] text-[var(--teal)]"><span className="grid h-[1.7vw] w-[1.7vw] place-items-center rounded-full bg-[rgba(131,184,171,.18)]"><ThumbsUp size=".85vw" /></span><span className="text-[clamp(11px,.95vw,15px)] font-semibold">Accepted</span></div><div className="mt-[1vw] text-[clamp(8px,.65vw,11px)] leading-[1.4] text-[var(--paper-dim)]">Evidence supports the model's proposed root cause.</div></motion.div></div>
        <motion.div className="mt-[.8vw] rounded-[.3vw] border border-[var(--line)] p-[.85vw]" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.15, duration: .5 }}><div className="flex items-center gap-[.5vw]"><FileCheck2 size="1vw" className="text-[var(--amber)]" /><span className="mono text-[clamp(7px,.53vw,10px)] text-[var(--muted)]">REVIEW NOTE</span></div><div className="mt-[.55vw] text-[clamp(8px,.67vw,11px)] text-[var(--paper-dim)]">"Matches the native VLAN mismatch observed in both switch outputs."</div></motion.div>
        <div className="mt-[1vw] flex items-center gap-[.6vw] text-[var(--teal)]"><Check size="1vw" /><span className="mono text-[clamp(7px,.55vw,10px)]">AUDIT RECORD SAVED LOCALLY</span><span className="ml-auto mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">10:42:18 UTC</span></div>
      </motion.div>
    </motion.section>
  );
}