import { motion } from 'framer-motion';
import { BrainCircuit, ChevronRight, Sparkles } from 'lucide-react';

export function Scene4() {
  return (
    <motion.section className="relative h-screen w-full overflow-hidden" initial={{ opacity: 0, scale: 1.08, clipPath: 'inset(0 100% 0 0)' }} animate={{ opacity: 1, scale: 1, clipPath: 'inset(0 0% 0 0)' }} exit={{ opacity: 1, scale: .94, clipPath: 'inset(0 0 0 100%)' }} transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}>
      <img src={`${import.meta.env.BASE_URL}media/netsage-reasoning-field.png`} alt="" className="absolute inset-0 h-full w-full object-cover opacity-[.26] mix-blend-screen" />
      <div className="absolute inset-0 bg-[linear-gradient(100deg,rgba(21,27,32,.97),rgba(21,27,32,.58) 47%,rgba(21,27,32,.88))]" />
      <motion.div className="absolute left-[47vw] top-[16vh] h-[29vw] w-[29vw] rounded-full border border-[rgba(226,111,88,.26)]" animate={{ rotate: [0, -360] }} transition={{ duration: 22, repeat: Infinity, ease: 'linear' }} />
      <motion.div className="absolute left-[51vw] top-[20vh] h-[21vw] w-[21vw] rounded-full border border-dashed border-[rgba(131,184,171,.35)]" animate={{ rotate: [360, 0] }} transition={{ duration: 14, repeat: Infinity, ease: 'linear' }} />
      <div className="absolute left-[4.4vw] top-[16vh]"><div className="caption mb-[2.5vh] text-[var(--coral)]">03 / Make a bounded hypothesis</div><h2 className="display-lg">Signals in.<br /><span className="text-[var(--coral)]">Clarity out.</span></h2><p className="body-sm mt-[3vh] max-w-[23vw] text-[var(--paper-dim)]">The model never gets to improvise outside the packet. It turns validated evidence into a ranked next move.</p></div>
      <motion.div className="absolute left-[51vw] top-[30vh] w-[37vw] -translate-x-1/2" initial={{ opacity: 0, scale: .84 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .45, duration: 1.1, ease: [0.16, 1, 0.3, 1] }}>
        <div className="relative rounded-full border border-[rgba(226,111,88,.45)] bg-[rgba(21,27,32,.78)] p-[.4vw] shadow-[0_0_5vw_rgba(226,111,88,.16)]"><div className="rounded-full border border-[rgba(242,238,230,.12)] px-[4vw] py-[3.6vw] text-center"><BrainCircuit className="mx-auto mb-[1vw] text-[var(--coral)]" size="2.5vw" /><div className="mono text-[clamp(7px,.55vw,10px)] tracking-[.15em] text-[var(--muted)]">ROOT CAUSE HYPOTHESIS</div><div className="mt-[.8vw] text-[clamp(13px,1.35vw,22px)] font-semibold leading-[1.12]">Native VLAN mismatch<br />on the trunk link</div><div className="mt-[1.1vw] flex items-center justify-center gap-[.55vw]"><span className="mono text-[clamp(8px,.65vw,11px)] text-[var(--coral)]">92% CONFIDENCE</span><span className="h-[.35vw] w-[7vw] overflow-hidden rounded-full bg-[rgba(242,238,230,.1)]"><motion.span className="block h-full w-[92%] bg-[var(--coral)]" initial={{ scaleX: 0, transformOrigin: 'left' }} animate={{ scaleX: 1 }} transition={{ delay: 1.1, duration: .9 }} /></span></div></div></div>
        <div className="mt-[1.1vw] grid grid-cols-2 gap-[.6vw]"><motion.div className="rounded-[.3vw] border border-[var(--line)] bg-[rgba(21,27,32,.84)] p-[.8vw]" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.1, duration: .5 }}><div className="mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">NEXT COMMAND</div><div className="mt-[.55vw] mono text-[clamp(8px,.62vw,11px)] text-[var(--teal)]">show interfaces trunk</div></motion.div><motion.div className="rounded-[.3vw] border border-[var(--line)] bg-[rgba(21,27,32,.84)] p-[.8vw]" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.28, duration: .5 }}><div className="mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">EVIDENCE USED</div><div className="mt-[.55vw] flex items-center gap-[.3vw] text-[clamp(8px,.62vw,11px)] text-[var(--paper)]"><Sparkles size=".8vw" className="text-[var(--amber)]" /> 3 validated signals</div></motion.div></div>
      </motion.div>
      <div className="absolute bottom-[13vh] left-[4.4vw] flex items-center gap-[.55vw] text-[var(--muted)]"><span className="mono text-[clamp(8px,.6vw,10px)]">AI ANALYSIS</span><ChevronRight size=".9vw" className="text-[var(--coral)]" /><span className="mono text-[clamp(8px,.6vw,10px)] text-[var(--paper-dim)]">TRACEABLE · BOUNDED · ACTIONABLE</span></div>
    </motion.section>
  );
}