import { motion } from 'framer-motion';
import { Activity, ArrowUpRight, Check, History, Sparkles } from 'lucide-react';

const bars = [34, 48, 41, 67, 56, 76, 69, 88, 73, 92, 84, 98];

export function Scene6() {
  return (
    <motion.section className="relative h-screen w-full overflow-hidden" initial={{ opacity: 0, clipPath: 'inset(100% 0 0 0)' }} animate={{ opacity: 1, clipPath: 'inset(0% 0 0 0)' }} exit={{ opacity: 1, clipPath: 'inset(0 0 100% 0)' }} transition={{ duration: .95, ease: [0.16, 1, 0.3, 1] }}>
      <div className="absolute inset-0 bg-[linear-gradient(120deg,#151b20,#1d2b2e_60%,#24302e)]" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_30%,rgba(131,184,171,.18),transparent_32%)]" />
      <div className="absolute left-[4.4vw] top-[18vh]"><div className="caption mb-[2.2vh] text-[var(--teal)]">05 / Learn from every decision</div><h2 className="display-lg">The queue gets<br /><span className="text-[var(--teal)]">smarter.</span></h2><p className="body-sm mt-[3vh] max-w-[22vw] text-[var(--paper-dim)]">Analytics make quality visible. Audit trails turn one good fix into a better operating system.</p><div className="mt-[4vh] flex items-center gap-[.6vw]"><Sparkles size="1vw" className="text-[var(--amber)]" /><span className="mono text-[clamp(8px,.6vw,10px)] text-[var(--amber)]">11 CORRECTIONS FED BACK THIS SHIFT</span></div></div>
      <motion.div className="absolute right-[5vw] top-[15vh] w-[49vw] rounded-[.45vw] border border-[var(--line)] bg-[rgba(21,27,32,.76)] p-[1.25vw] backdrop-blur" initial={{ opacity: 0, scale: .95, x: 40 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ delay: .4, duration: .85, ease: [0.16, 1, 0.3, 1] }}>
        <div className="flex items-center justify-between border-b border-[var(--line)] pb-[1vw]"><div className="flex items-center gap-[.6vw]"><Activity size="1vw" className="text-[var(--teal)]" /><div><div className="mono text-[clamp(7px,.52vw,10px)] text-[var(--muted)]">ANALYTICS / DECISION QUALITY</div><div className="mt-[.25vw] text-[clamp(13px,1.1vw,18px)] font-semibold">Where the queue stands</div></div></div><span className="mono text-[clamp(7px,.5vw,9px)] text-[var(--teal)]">LIVE</span></div>
        <div className="mt-[1vw] grid grid-cols-[1.35fr_.75fr] gap-[.7vw]"><div className="rounded-[.3vw] border border-[var(--line)] p-[.9vw]"><div className="flex justify-between"><span className="mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">AI / HUMAN AGREEMENT</span><span className="mono text-[clamp(8px,.62vw,11px)] text-[var(--teal)]">86%</span></div><div className="mt-[1.2vw] flex h-[10vw] items-end gap-[.45vw] border-b border-[var(--line)] px-[.3vw]">{bars.map((height, index) => <motion.span key={index} className="flex-1 rounded-t-[.18vw] bg-[var(--teal)]" initial={{ height: 0 }} animate={{ height: `${height}%` }} transition={{ delay: .65 + index * .05, duration: .45, ease: [0.16, 1, 0.3, 1] }} />)}</div><div className="mt-[.55vw] flex justify-between mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]"><span>MON</span><span>SUN</span></div></div><div className="rounded-[.3vw] border border-[var(--line)] p-[.9vw]"><div className="mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">SHIFT SIGNALS</div><div className="mt-[1vw] space-y-[.75vw]"><div><div className="flex justify-between text-[clamp(8px,.62vw,11px)]"><span>Rules passed</span><span className="mono text-[var(--teal)]">92%</span></div><div className="mt-[.35vw] h-[.3vw] rounded-full bg-[rgba(242,238,230,.1)]"><motion.div className="h-full w-[92%] rounded-full bg-[var(--teal)]" initial={{ scaleX: 0, transformOrigin: 'left' }} animate={{ scaleX: 1 }} transition={{ delay: 1, duration: .7 }} /></div></div><div><div className="flex justify-between text-[clamp(8px,.62vw,11px)]"><span>Cases resolved</span><span className="mono text-[var(--amber)]">68%</span></div><div className="mt-[.35vw] h-[.3vw] rounded-full bg-[rgba(242,238,230,.1)]"><motion.div className="h-full w-[68%] rounded-full bg-[var(--amber)]" initial={{ scaleX: 0, transformOrigin: 'left' }} animate={{ scaleX: 1 }} transition={{ delay: 1.15, duration: .7 }} /></div></div></div><div className="mt-[1.4vw] border-t border-[var(--line)] pt-[.8vw]"><div className="mono text-[clamp(7px,.5vw,9px)] text-[var(--muted)]">AUDIT TRAIL</div><div className="mt-[.45vw] flex items-center gap-[.45vw] text-[var(--paper-dim)]"><History size=".85vw" className="text-[var(--amber)]" /><span className="text-[clamp(8px,.62vw,11px)]">178 decisions traceable</span></div></div></div></div>
        <motion.div className="mt-[.85vw] flex items-center justify-between rounded-[.3vw] border border-[rgba(131,184,171,.25)] bg-[rgba(131,184,171,.06)] p-[.8vw]" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.45, duration: .5 }}><div className="flex items-center gap-[.5vw]"><span className="grid h-[1.5vw] w-[1.5vw] place-items-center rounded-full bg-[var(--teal)] text-[var(--ink)]"><Check size=".8vw" /></span><span className="text-[clamp(9px,.75vw,13px)] font-semibold">One continuous evidence loop</span></div><ArrowUpRight size="1vw" className="text-[var(--teal)]" /></motion.div>
      </motion.div>
      <motion.div className="absolute bottom-[12vh] left-[4.4vw] flex items-center gap-[.6vw]" initial={{ opacity: 0, x: -15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 1.4, duration: .5 }}><span className="h-[.5vw] w-[.5vw] rounded-full bg-[var(--coral)]" /><span className="mono text-[clamp(8px,.65vw,11px)] tracking-[.12em] text-[var(--paper)]">NETSAGE AI CONSOLE</span><span className="mono text-[clamp(8px,.55vw,10px)] text-[var(--muted)]">/ EVIDENCE-DRIVEN NETWORK INTELLIGENCE</span></motion.div>
    </motion.section>
  );
}